### PR TITLE
Result.forEach with tests and docs

### PR DESCRIPTION
**Pull request by jmagaram**
Analogous to Array.forEach and Option.forEach. In nearly every other standard library of Result/Either types.

### CODE REVIEW

**Review by glennsl — APPROVED** [review]

**Comment by zth** [comment]
Oh, one final thing @jmagaram - please add an entry to the changelog. Then this is mergeable.

**Comment by jmagaram** [comment]
> Oh, one final thing @jmagaram - please add an entry to the changelog. Then this is mergeable.

Sorry don't know how to do that. Is this 0.2.0? Where does it go in that doc?

**Comment by zth** [comment]
Just add a new "API changes" under "main", like now exists under "0.2.0", and add your entry there.

**Comment by jmagaram** [comment]
I'll try to collect the object documentation PRs but I'm expecting to be paid separately for each one! Actually I don't know how to combine them. Will try to learn.

**Pull request merged**
