### PR TITLE
Int: Add bitwise functions from Pervasives

### PR DESCRIPTION
**Pull request by fhammerschmidt**

### CODE REVIEW

**Comment by fhammerschmidt** [comment]
@cometkim fyi

**Comment by cometkim** [comment]
BigInt needs this too

**Comment by fhammerschmidt** [comment]
BigInt has a lot of missing docs so I will do that in a separate PR.

We also have the chance here to rename the functions into more descriptive ones, if we want.

lsl => logicalShiftLeft
lsl => logicalShiftRght
lxor => logicalXor
etc.

if we later on have operators for those functions anyway it would not matter as much if the names are longer.

**Comment by cometkim** [comment]
> We also have the chance here to rename the functions into more descriptive ones, if we want.

We can "add", not rename

Even we support infix ops, the shorter names are still useful for those who prefer the pipe style.

**Comment by fhammerschmidt** [comment]
@zth As mentioned in discord, I just keep it as it is. Merge?

**Comment by zth** [comment]
Got for it!

**Comment by zth** [comment]
Got for it!

**Comment by fhammerschmidt** [comment]
wait, I need to put them in their own submodule first

**Pull request merged**
