### PR TITLE
Object.assign documentation and tests

### PR DESCRIPTION
**Pull request by jmagaram**
This took me a while because I wrote some tests to experiment and got the source and target mixed up - the mutable target goes first. Should we have labels on these?

I attempted to write code for `assignMany` but it doesn't work because you can't create an array of objects with different types. Well you can I guess if they start off as Object.empty() or are imported - jumping through hoops. Will this really get used? Do we need a `toGenericObject` function?

I couldnt' figure out the other flavor of assign with the json thing and what it does.

### CODE REVIEW

**Review by zth — APPROVED** [review]
Looking great!

Good point about `assignMany`. I think we can leave it undocumented for now. The `Object` module is for more specialized usage anyway.

**Comment by glennsl** [comment]
But you can also just chain calls to `assign`, so... :shrug:

**Comment by jmagaram** [comment]
Interesting idea on the `assign2` `assign3` - hadn't thought about that. I don't know when any of these functions will get used from ReScript, if ever. I wouldn't mind removing the `assignMany` and rely on chaining calls. A `toUntypedObject` could normalize objects in a list so `assignMany` will work. You all have much more real-world experience and know better what is needed here.

**Comment by jmagaram** [comment]
Consolidated into https://github.com/rescript-association/rescript-core/pull/117

**Pull request closed without merging**
