### PR TITLE
compare and equal

### PR DESCRIPTION
**Pull request by cknitt**
Add compare and equal functions, see #77.

Modules:

- [x] Array
- [x] Int
- [x] Float
- [x] String
- [x] Date
- [x] Null
- [x] Nullable

TODO:

- [ ] Docs
- [ ] Tests

### CODE REVIEW

**Comment by jmagaram** [comment]
I put some comments in the issue. I think we should discuss there, not here. I see problems using `compare` with options when sorting arrays - data first is awkward. Same with instantiating a Belt.Set or Map. I'm not sure where data first really works for option since you're going to end up with a number like -1, 0, or 1 and then what to do with it? Also does the subtraction implementation for int.compare work with NaN and other weird cases; it might.
```
let compareInt = (x, y) => x < y ? -1 : x > y ? 1 : 0
let x = [Some(1), None, Some(5), Some(2)]->Array.sortInPlace((a, b) => Option.cmp(a, b, compareInt))
```

**Comment by jmagaram** [comment]
The implementation fails with overflow like `Int.Constants.minValue - Int.Constants.maxValue `. I'd recommend this. Make sure to explicitly specify the types or else you'll end up with `Call_obj.lessthan`.
```
let compare = (x: int, y: int) => x < y ? -1 : x > y ? 1 : 0
```

**Comment by jmagaram** [comment]
Might want to explain in the docs which equality operator is used for floats/ints. if you use === then NaN != NaN and -0.0==+0.0 which seems fine to me. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

**Comment by jmagaram** [comment]
I'm confused about the string compare flavors. How does the version you've coded relate to `String.localeCompare` with or without options? Is there any advantage to it? The docs should explain when to use which ones. I'm wondering if these compare options should be grouped/unified together so the developer can easily see their choices together. Maybe `String.compareLocale`, `String.compareLocaleWith`, and `String.compare`, where the last is the version you've coded and the first two are the `String.localeCompare` versions with and without options.

https://262.ecma-international.org/7.0/#sec-abstract-relational-comparison

**Review by cristianoc — APPROVED** [review]

**Pull request merged**
