### PR TITLE
chore(ci): add style check workflow

### PR DESCRIPTION
**Pull request by glennsl**

### CODE REVIEW

**Comment by glennsl** [comment]
Tested that it fails when it should on my own fork. See https://github.com/glennsl/rescript-core/actions

**Comment by zth** [comment]
Cool! Can we add a description somewhere that shows up in GitHub that you'll need to format all files (and point to the command to do that)? Just do people understand what's wrong when this fails.

**Comment by glennsl** [comment]
Done. See https://github.com/glennsl/rescript-core/actions/runs/4217814412 for an example.

**Comment by zth** [comment]
Fantastic, thank you very much!

**Pull request merged**
