### PR TITLE
Use native bigint type

### PR DESCRIPTION
**Pull request by fhammerschmidt**

### CODE REVIEW

**Comment by zth** [comment]
This is great! But let's do a normal release first so we can bump to 11.1 for the next one. I'll sort it out soon.

**Comment by fhammerschmidt** [comment]
actually adapted it to be basically the same as Js.Bigint, since now we can do (and document) just a 
`open! BigInt` when Core is open.

**Comment by fhammerschmidt** [comment]
With rc-7 the doc tests succeed!

**Comment by zth** [comment]
I'll make a new release soon and we can get this merged after.

**Comment by zth** [comment]
@fhammerschmidt rebase and we're ready to go!

**Pull request merged**
