### PR TITLE
Added random_int to Core__Math

### PR DESCRIPTION
**Pull request by adhi-27**

### CODE REVIEW

**Comment by DZakh** [comment]
Hi, it should be added in the module https://github.com/rescript-association/rescript-core/blob/106a882283806ec130e37a1a8781f0b0c41578e5/src/Core__Math.res#L12

**Comment by zth** [comment]
Looking good! We'll need docstrings and tests for this too.

**Comment by adhi-27** [comment]
> Looking good! We'll need docstrings and tests for this too.

Added docstrings and tests

**Review by zth — APPROVED** [review]
Great stuff, thank you! Mind adding a changelog too?

**Comment by adhi-27** [comment]
> Great stuff, thank you! Mind adding a changelog too?

Added the changelog

**Comment by zth** [comment]
@adhi-27 I think the changelog entries ended up in the wrong place. They should be directly under the "main" entry at the top. Looks like there are no current entries there, so you'll also need to add the sub headlines (Documentation etc).

**Pull request merged**
